###
GET http://localhost:8080/webclient

> {%

    client.test("assert 200 status", function () {
        client.assert(response.status === 200, "expected 200: but: " + response.status);
    });

%}

###
GET http://localhost:8080/webclient

> {%

    client.test("assert 200 status", function () {
        client.assert(response.status === 200, "expected 200: but: " + response.status);
    });

%}

###
GET http://localhost:8080/webclient

> {%

    client.test("assert 200 status", function () {
        client.assert(response.status === 200, "expected 200: but: " + response.status);
    });

%}

###
GET http://localhost:8080/webclient

> {%

    client.test("assert 200 status", function () {
        client.assert(response.status === 200, "expected 200: but: " + response.status);
    });

%}

###
GET http://localhost:8080/webclient

> {%

    client.test("assert 200 status", function () {
        client.assert(response.status === 200, "expected 200: but: " + response.status);
    });

%}

###
GET http://localhost:8080/webclient

> {%

    client.test("assert 200 status", function () {
        client.assert(response.status === 200, "expected 200: but: " + response.status);
    });

%}

###
GET http://localhost:8080/webclient

> {%

    client.test("assert 200 status", function () {
        client.assert(response.status === 200, "expected 200: but: " + response.status);
    });

%}

###
GET http://localhost:8080/webclient

> {%

    client.test("assert 200 status", function () {
        client.assert(response.status === 200, "expected 200: but: " + response.status);
    });

%}

###
GET http://localhost:8080/webclient

> {%

    client.test("assert 200 status", function () {
        client.assert(response.status === 200, "expected 200: but: " + response.status);
    });

%}

###
GET http://localhost:8080/webclient

> {%

    client.test("assert 200 status", function () {
        client.assert(response.status === 200, "expected 200: but: " + response.status);
    });

%}