spring:
  application:
    name: a-service
  output:
    ansi:
      enabled: always
  cloud:
    aws:
      endpoint: http://localhost:4566
      region:
        static: us-west-1
      credentials:
        access-key: noop
        secret-key: noop
    stream:
      bindings:
        outputsns-out-0:
          destination: arn:aws:sns:us-west-1:000000000000:sns-1 # need to change every time it is provision
          content-type: application/json
          binder: sns
    function:
      definition: outputsns

server:
  port: 8080

b-service:
  url: http://localhost:8081

#management:
#  tracing:
#    baggage:
#      remote-fields: email
#      correlation:
#        fields: email
#    propagation:
#      type: w3c
#
#
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %thread - %X{traceId} - %X{power} -%X{customerId} - %msg%n"
management:
  tracing:
    baggage:
      correlation:
        fields: orderId, customerId, power
        enabled: true
      remote-fields: orderId, customerId, power
#    propagation:
#      produce: [b3,w3c]
#      consume: [b3,w3c]
