spring:
  application:
    name: a-service
  output:
    ansi:
      enabled: always
server:
  port: 8080

b-service:
  url: http://localhost:8081

management:
  tracing:
    baggage:
      remote-fields: email, power
      correlation:
        fields: email
        enabled: true

logging:
  pattern:
    console: "%d{HH:mm:ss} - %t %X{traceId} %X{spanId} %X{email} %X{power}- %msg%n"

otel:
  logs:
    exporter: none
  metrics:
    exporter: none
  traces:
    exporter: none

