spring:
  application:
    name: a-service
  output:
    ansi:
      enabled: always
server:
  port: 8080

b-service:
  url: http://localhost:8081

management:
  tracing:
    baggage:
      remote-fields: email
      correlation:
        fields: email
        enabled: true


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} -  %X{email} - %X{traceId} - %X{spanId} - %t - %msg%n"

otel:
  logs:
    exporter: none
  metrics:
    exporter: none
  traces:
    exporter: none

