server:
  port: 8080
spring:
  application:
    name: a-service
  threads:
    virtual:
      enabled: true
  output:
    ansi:
      enabled: always
  devtools:
    restart:
      enabled: true
  cloud:
    aws:
      endpoint: http://localhost:4566
      region:
        static: us-west-1
      credentials:
        access-key: noop
        secret-key: noop
    stream:

      bindings:
        ptmsns-out-0:
          destination: arn:aws:sns:us-west-1:000000000000:sns-1 # need to change every time it is provision
          binder: sns


b-service:
  url: http://localhost:8081

management:
  tracing:
    baggage:
      remote-fields: email, power
      correlation:
        fields: email
        enabled: true

#logging:
#  pattern:
#    console: "%d{HH:mm:ss} - %t %X{traceId} %X{spanId} %X{email} %X{power}- %msg%n"

otel:
  logs:
    exporter: none
  metrics:
    exporter: none
  traces:
    exporter: none
  propagators: [tracecontext,baggage]
  resource:
    attributes:
      service:
        name: a-service
        namespace: micro-a-b

